# Generated by Django 4.2.11 on 2025-01-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, default='noImage.png', upload_to='', verbose_name='店舗画像'),
        ),
    ]
