# Generated by Django 4.2.11 on 2025-01-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0004_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_shop',
            field=models.ManyToManyField(blank=True, to='tabelog.shop', verbose_name='お気に入り店舗'),
        ),
    ]
